### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Object of type Button is not JSON serializable

### ISSUE THREAD

**Issue by Ayensha** [Polsulpicien/discord.py-advanced-calculator#4]
![image](https://user-images.githubusercontent.com/97728392/153468800-2b44d626-09dd-4146-90d2-cd13b70a5304.png)

How do i fix it?

**Comment by Polsulpicien** [comment]
> ![image](https://user-images.githubusercontent.com/97728392/153468800-2b44d626-09dd-4146-90d2-cd13b70a5304.png)
> 
> How do i fix it?

What library are you using ? (discord.py ?) And please also provide the version of it.

Note: discord-components is a deprecated library (still works) and will not work with discord.py 2.0

**Comment by Ayensha** [comment]
![image](https://user-images.githubusercontent.com/97728392/153639184-18e3f8ef-6988-4ad8-acc5-6056fc14bc70.png)

i am using discord.py version is 1.7.3

**Comment by Polsulpicien** [comment]
Have you ever installed any discord.py forks ? If yes please delete them and try again 👀 
Are you using the cog or main file ?

If you are using the cog, did you update your main file ?
```py
@client.event
async def on_ready():
    DiscordComponents(client)
```
and:
```py
client = commands.Bot(command_prefix = "&", intents=discord.Intents.all())
```
**discord.Intents.all()**

Could you join the support server and open a ticket please ? It will be easier to fix your issue :)
https://discord.gg/xm9QX3Q

**Comment by Ayensha** [comment]
> Have you ever installed any discord.py forks ? If yes please delete them and try again 👀 
> Are you using the cog or main file ?
> 
> If you are using the cog, did you update your main file ?
> ```py
> @client.event
> async def on_ready():
>     DiscordComponents(client)
> ```
> and:
> ```py
> client = commands.Bot(command_prefix = "&", intents=discord.Intents.all())
> ```
> **discord.Intents.all()**
> 
> Could you join the support server and open a ticket please ? It will be easier to fix your issue :)
> https://discord.gg/xm9QX3Q

Ok
